mint.preload.json.output=scripts/preload-test-data.json
mint.preload.mint-id=11111111-1111-1111-1111-111111111111
mint.preload.sql.input=scripts/preload-test-data.json
mint.preload.sql.output=scripts/preload-test-data.sql
