cashu.units=sat

# Expiry time in minutes
cashu.expiry=15

gateway.prod=xyz.tcheeric.gateway.phoenixd.PhoenixdGateway
gateway.mock=xyz.tcheeric.gateway.mock.PhoenixdMockGateway
cashu.melt.fee-reserve-percent=0.05
