-- Who changed operator access, and to whom. Separate from audit_events, which is
-- keyed by mint: access management is not about a mint. Append-only — a suspended
-- Operator must stay resolvable from the trail, the same rule that keeps Archived
-- Keysets rather than deleting them.
CREATE TABLE operator_access_audit (
    entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor VARCHAR(255) NOT NULL,
    action VARCHAR(64) NOT NULL,
    target_account_id VARCHAR(255) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_operator_access_audit_target ON operator_access_audit (target_account_id, occurred_at);
